version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_kodija
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:delegated
            - vendor:/var/www/html/vendor
            - storage:/var/www/html/storage
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: base64:oBoYSgB5ng8y8+fwkHFtN3xLItf66OCR8Yj9SjaZCbQ=
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: db_kodija
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db_kodija
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        ports:
            - "8000:80"
        environment:
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db

volumes:
    db_data:
    vendor:
    storage:
